apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name }}-service-grpc-gateway
  labels:
    app: {{ include "backend.name" . }}
    chart: {{ include "backend.chart" . }}
    app_label: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Value.service.type }}
  ports:
    - name: grpc-gateway
      port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: {{ .Value.service.port }}
    - name: grpc-gateway-rpc
      port: 7070
      protocal: TCP
      targetPort: 7070
  selector:
    app: {{ template "backend.name" }}
    app_label: {{ .Release.Name }}