apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-gateway
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - replicationcontrollers
  - events
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resource:
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resource:
  - namespaces
  verbs:
  - get
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-gateway
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
