FROM centos
WORKDIR /root
COPY container/ .
#COPY mysql/ mysql/
#RUN yum install -y --downloadonly --downloaddir=/root/mysql/ /root/mysql/mysql-community-release-el7-5.noarch.rpm
#ENTRYPOINT ["bash", "/root/start.sh"]