// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Null)(nil), "protos.Null")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x52, 0x32,
	0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25,
	0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0x55, 0x4a, 0x6c, 0x5c, 0x2c, 0x7e, 0xa5, 0x39, 0x39,
	0x46, 0xce, 0x5c, 0xbc, 0xee, 0xa9, 0x25, 0xe5, 0x89, 0x95, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9,
	0xa9, 0x42, 0x46, 0x5c, 0x6c, 0xee, 0xa9, 0x25, 0x8e, 0x39, 0x39, 0x42, 0x3c, 0x10, 0xa5, 0xc5,
	0x7a, 0x20, 0x85, 0x52, 0x28, 0x3c, 0x25, 0x9e, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0xb1, 0x09, 0xb1,
	0xe8, 0xa7, 0xa7, 0x96, 0x24, 0x41, 0xac, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x72, 0x64,
	0xfc, 0x37, 0x8a, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetwayServiceClient is the client API for GetwayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetwayServiceClient interface {
	GetAll(ctx context.Context, in *Null, opts ...grpc.CallOption) (*Null, error)
}

type getwayServiceClient struct {
	cc *grpc.ClientConn
}

func NewGetwayServiceClient(cc *grpc.ClientConn) GetwayServiceClient {
	return &getwayServiceClient{cc}
}

func (c *getwayServiceClient) GetAll(ctx context.Context, in *Null, opts ...grpc.CallOption) (*Null, error) {
	out := new(Null)
	err := c.cc.Invoke(ctx, "/protos.GetwayService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetwayServiceServer is the server API for GetwayService service.
type GetwayServiceServer interface {
	GetAll(context.Context, *Null) (*Null, error)
}

// UnimplementedGetwayServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGetwayServiceServer struct {
}

func (*UnimplementedGetwayServiceServer) GetAll(ctx context.Context, req *Null) (*Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}

func RegisterGetwayServiceServer(s *grpc.Server, srv GetwayServiceServer) {
	s.RegisterService(&_GetwayService_serviceDesc, srv)
}

func _GetwayService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Null)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetwayServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GetwayService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetwayServiceServer).GetAll(ctx, req.(*Null))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetwayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.GetwayService",
	HandlerType: (*GetwayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _GetwayService_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
